workflows:
  android-workflow:
    name: Ahmodia Android Build
    max_build_duration: 60
    environment:
      flutter: 3.19.6
      java: 17
    scripts:
      - name: Get Flutter packages
        script: |
          cd $CM_BUILD_DIR/ahmodia_app
          flutter pub get
      - name: Generate launcher icons
        script: |
          chmod +x $CM_BUILD_DIR/generate_icons.sh
          $CM_BUILD_DIR/generate_icons.sh
      - name: Build APK
        script: |
          cd $CM_BUILD_DIR/ahmodia_app
          flutter build apk --debug
    artifacts:
      - ahmodia_app/build/**/outputs/**/*.apk
